public enum GameSection{
	NONE									= -3,
	SOME									= -2,
	ALL										= -1,
	
	CORPORATIVE_LOGO_SPLASH 				= 0,
	LOAD_SCREEN 							= 1,
	MAIN_MENU 								= 2,
	SETTINGS 								= 3,
	CREDITS 								= 4,
	LEVEL_SELECTION 						= 5,
	GAME 									= 6,
	QUICKGAME_MODE							= 7,
	CAMPAIGN_MODE							= 8,
	SURVIVAL_MODE							= 9, 									
	PAUSE 									= 10,
	COMPLETED_LEVEL 						= 11,
	MORE_GAMES								= 12,
	ENVIRONMENT_SELECTION					= 13,
	CHARACTER_SELECTION						= 14,
	ITEMS_SELECTION							= 15,
	TUTORIAL								= 16,
	IN_APP									= 17,
}