public enum GameScreen{
	LEVEL_CONFIRMATION 				= 0,
	EXIT							= 1,
	PAUSE							= 2,
	SHOW_MISSION					= 3,
	GAMEOVER						= 4,
	COMPLETED_MISSION				= 5,
	CONNECTING_FACEBOOK				= 6,
	FACEBOOK_ACCOUNT_CONNECTED		= 7,
	FACEBOOK_FAILED_CONNECTION		= 8,
	FACEBOOK_FRIENDS_INVITATION		= 9,
	BACK_COUNTER					= 10, //3, 2, 1.. GO!
	POPUP_ALERT_PURCHASE_ITEM		= 11
}