public enum Section{
	CORPORATIVE_LOGO_SPLASH 				= 0,
	LOAD_SCREEN 							= 1,
	MAIN_MENU 								= 2,
	SETTINGS 								= 3,
	CREDITS 								= 4,
	LEVEL_SELECTION 						= 5,
	GAME 									= 6,
	PAUSE 									= 7,
	COMPLETED_LEVEL 						= 8,
	MORE_GAMES								= 9,
	ENVIRONMENT_SELECTION					= 10,
	CHARACTER_SELECTION						= 11,
	TUTORIAL								= 12,
}