public enum UIFunction{
	NONE									= -1
	,SOME
	,ALL

	,MAIN_MENU_SCREEN
	,MAIN_MENU_SCREEN_FROM_GAME_SCREEN
	,MAIN_MENU_FROM_INFO_SCREEN
	,MAIN_MENU_WITH_COMFIRMATION
	
	,SETTINGS_SCREEN
	,INFO_SCREEN
	,GAME_SCREEN
	,SHOW_QUEST_SCREEN
	,TUTORIAL_SCREEN
	,ACHIEVEMENTS_SCREEN
	,RANKINGS_SCREEN
	,RANKING_SCREEN_SWITCH_DIFFICULT
	,MORE_GAMES_SCREEN
	,PAUSE_GAME
	,RESUME_GAME
	,SELECT_CHARACTER
	,SELECT_WORLD
	
	,ELECCION_NIVEL
	
	,ACCEPT_QUEST
	,CONTINUE_HISTORY_MODE
	
	,QUICK_GAME_MODE
	,SURVIVAL_MODE
	,HISTORY_MODE
	
	,MUSIC_ACTIVATION
	,SOUND_ACTIVATION
	
	,LOGIN_GPS
	,LOGIN_GC
	,LOGIN_FB
	,LOGIN_TW
	
	,ABRIR_MENU_INVITAR_AMIGOS_FB
	,INVITAR_AMIGOS_FB
	
	,EASY_MODE
	,NORMAL_MODE
	,HARD_MODE
	,NONE_DIFFICULT_MODE
	
	,TEST_INC_POINTS
	,TEST_RESET_HISTORY
	
}