public enum AchieveCondition{
	
	ACTIVE_IF_LOWER_THAN		= -1,
	ACTIVE_IF_EQUALS_TO			= 0,
	ACTIVE_IF_GREATER_THAN		= 1,
	ACTIVE_IF_BETWEEN			= 2,
	ACTIVE_IF_LOWER_OR_EQUALS	= 3,
	ACTIVE_IF_GREATER_OR_EQUALS	= 4,
}